Factory Reset and RDM added
carallon/pharos-controller-api pull request #1
Opened 2022-03-09 15:02 UTC by Clarence-F

Trial addition of adding RDM and Factory Reset to the YAML

2022-03-10 17:23 UTC, sjmh3 requested changes

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/factory-reset.rst
> +Reboots the controller and wipes all settings off the unit.
```suggestion
Deletes all controller settings and reboots the unit.
```

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/rdm.rst
> +##############
```suggestion
#############
```

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/rdm.rst
> +===
```suggestion
====
```

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/rdm.rst
> +Returns RDM data from fixtures, or triggers an RDM scan on the desired controller.
```suggestion
Discover RDM fixtures and get cached device info from discovered fixtures.
```

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/rdm.rst
> +.. _discover-http-get:
Do you need this target? I generally only add these if they're needed.

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/rdm.rst
> +.. _discover-http-post:
Do you need this target?

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/rdm.rst
> +??? - Not sure how to get this info...?
In the query.js file - I sent you v5 & v6 for you to compare.

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/rdm.rst
> +Returns a JSON object with the following attributes:
This is wrong, but it's wrong because the YAML is wrong. It returns an array of device info for a particular universe. YAML needs updating before you can progress.

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/rdm.rst
> +``POST /api/rdm/discovery``
I show the query string params in this line, e.g. see the GET in web-api/output.rst

2022-03-10 17:23 UTC, sjmh3 commented on sphinx-src/web-api/rdm.rst
> +Triggers an RDM poll of the defined universe
See web-api/output.rst for the way to intro one of these GETs with a param in the query.

2022-03-11 13:42 UTC, Clarence-F commented
I've changed the pull requests, so we can close this off now, I think...

2022-11-02 19:44 UTC, closed without merging