V6 xpc dial
carallon/pharos-controller-api pull request #5
Opened 2022-03-11 14:12 UTC by Clarence-F

Added new XPC Dial Position page

2022-03-21 20:30 UTC, sjmh3 requested changes
You need to add this file to the index.

2022-03-21 20:30 UTC, sjmh3 commented on sphinx-src/web-api/xpc-mode.rst
> +.. note:: Expert only
```suggestion

.. note:: Expert only
```

2022-03-21 20:30 UTC, sjmh3 commented on sphinx-src/web-api/xpc-mode.rst
> +Gets the current mode dial position
```suggestion
Gets the current mode dial position.
```

2022-03-21 20:30 UTC, sjmh3 commented on sphinx-src/web-api/xpc-mode.rst
> +``Run``, ``Dmx1``, ``Dmx2``, ``Dali``, ``All``, ``Off``, ``PG1``, ``PG2``, ``PG3``, ``PG4``
Why not a list?

2022-03-21 20:31 UTC, sjmh3 requested changes
In fact, there's a whole chain of commits on this PR - this only needs 1 commit. We should review how you're creating these PRs.

2022-03-22 13:24 UTC, Clarence-F commented
> In fact, there's a whole chain of commits on this PR - this only needs 1 commit. We should review how you're creating these PRs.

This was mainly because of how I branched out this file, I comitted everything all together originally, so when I branched off this one, it started with the first 4 commits, which I then had to unthread manually, which autocommitted every time. Just part of my learning process, I understand it better now, so won't happen again.

2022-11-02 19:44 UTC, closed without merging